-- Add 9 TV Console Wall explore scenes so TV Wall cards on homepage link correctly.
-- Uses ON CONFLICT to skip if slugs already exist (e.g. from manual inserts).

BEGIN;

INSERT INTO explore_scenes (
  slug,
  title,
  description,
  room_type,
  hero_image_url,
  location,
  catalog_budget_ngn,
  minimum_item_price_ngn,
  status,
  sort_order,
  display_order,
  view_count,
  created_at,
  updated_at
) VALUES
  (
    'soft-life-minimalist',
    'Soft Life Minimalist',
    NULL,
    'tv_wall',
    'https://jvbrrgqepuhabwddufby.supabase.co/storage/v1/object/public/explore-inspirations/Soft%20Life%20Minimalist.png',
    'NG',
    0,
    0,
    'published',
    0,
    NULL,
    0,
    now(),
    now()
  ),
  (
    'midnight-blu-premium',
    'Midnight Blu Premium',
    NULL,
    'tv_wall',
    'https://jvbrrgqepuhabwddufby.supabase.co/storage/v1/object/public/explore-inspirations/Midnight%20Blu%20Premium.png',
    'NG',
    0,
    0,
    'published',
    0,
    NULL,
    0,
    now(),
    now()
  ),
  (
    'bookshelf-wall',
    'Bookshelf Wall',
    NULL,
    'tv_wall',
    'https://jvbrrgqepuhabwddufby.supabase.co/storage/v1/object/public/explore-inspirations/Bookshelf%20Wall.png',
    'NG',
    0,
    0,
    'published',
    0,
    NULL,
    0,
    now(),
    now()
  ),
  (
    'full-option',
    'Full Option',
    NULL,
    'tv_wall',
    'https://jvbrrgqepuhabwddufby.supabase.co/storage/v1/object/public/explore-inspirations/Full%20Option.png',
    'NG',
    0,
    0,
    'published',
    0,
    NULL,
    0,
    now(),
    now()
  ),
  (
    'oga-at-the-top',
    'Oga At The Top',
    NULL,
    'tv_wall',
    'https://jvbrrgqepuhabwddufby.supabase.co/storage/v1/object/public/explore-inspirations/Oga%20At%20The%20Top.png',
    'NG',
    0,
    0,
    'published',
    0,
    NULL,
    0,
    now(),
    now()
  ),
  (
    'arch-of-grace',
    'Arch Of Grace',
    NULL,
    'tv_wall',
    'https://jvbrrgqepuhabwddufby.supabase.co/storage/v1/object/public/explore-inspirations/Arch%20Of%20Grace.png',
    'NG',
    0,
    0,
    'published',
    0,
    NULL,
    0,
    now(),
    now()
  ),
  (
    'vibes-on-vibes',
    'Vibes On Vibes',
    NULL,
    'tv_wall',
    'https://jvbrrgqepuhabwddufby.supabase.co/storage/v1/object/public/explore-inspirations/Vibes%20on%20Vibes.png',
    'NG',
    0,
    0,
    'published',
    0,
    NULL,
    0,
    now(),
    now()
  ),
  (
    'marble-no-be-small',
    'Marble No Be Small',
    NULL,
    'tv_wall',
    'https://jvbrrgqepuhabwddufby.supabase.co/storage/v1/object/public/explore-inspirations/Marble%20No%20Be%20Small.png',
    'NG',
    0,
    0,
    'published',
    0,
    NULL,
    0,
    now(),
    now()
  ),
  (
    'wood-flute',
    'Wood Flute',
    NULL,
    'tv_wall',
    'https://jvbrrgqepuhabwddufby.supabase.co/storage/v1/object/public/explore-inspirations/Wood%20Flute.png',
    'NG',
    0,
    0,
    'published',
    0,
    NULL,
    0,
    now(),
    now()
  )
ON CONFLICT (slug) DO NOTHING;

COMMIT;
